import = [
  "~/dotfiles/terminal/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[window]
decorations = "Buttonless"
dynamic_padding = true
