"$schema" = 'https://starship.rs/config-schema.json'

format = """
$env_var\
[](color_bg1)\
${custom.start_symbol}\
$directory\
[](fg:color_bg1)\
$character"""

right_format = """
[](color_bg1)\
$git_status\
$git_branch\
${custom.end_symbol}\
[](fg:color_bg1)"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "fg:color_fg0 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
style = "bg:color_bg1"
format = '[[ $branch](fg:color_fg0 bg:color_bg1)]($style)'

[git_status]
style = "bg:color_bg1"
format = '[[($all_status$ahead_behind)](fg:color_red bg:color_bg1)]($style)'

[custom.end_symbol]
command = "echo ''"
when = "true"
style = "fg:color_red bg:color_bg1"
format = '[ $output ]($style)'

[custom.start_symbol]
command = "echo ' '"
when = "true"
style = "fg:color_orange bg:color_bg1"
format = '[$output]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[ ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ ](bold fg:color_yellow)'
