format = """
[█](#fabc2e)\
$directory\
[](fg:#fabc2e bg:#8ec07b)\
$git_branch\
$git_status\
[](fg:#8ec07b bg:#928373)\
$cmd_duration\
[ ](fg:#928373)\
\n$character"""

# Disable the blank line at the start of the prompt
add_newline = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#fabc2e fg:#272727"
format = "[$path]($style)"
truncation_length = 0
truncation_symbol = "~/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "fg:#272727 bg:#8ec07b"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#cc231c bg:#8ec07b"
format = '[$all_status$ahead_behind ]($style)'

[cmd_duration]
disabled = false
min_time = 500  # Duration is shown if command runs longer than 500ms
style = "fg:#ebdbb2 bg:#928373 "
format = '[ 󱦟 $duration ]($style)'
