"$schema" = 'https://starship.rs/config-schema.json'

format = """
$env_var\
[](color_orange)\
$directory\
[](fg:color_orange)\
$fill\
[](color_bg1)\
$git_status\
$git_branch\
[](bg:color_bg1 fg:color_orange)\
[](bg:color_orange fg:color_yellow)\
[](bg:color_yellow fg:color_aqua)\
[](bg:color_aqua fg:color_blue)\
[](bg:color_blue fg:color_bg1)\
$os\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[fill]
symbol = '·'
style = 'fg:color_fg0'

[os]
disabled = false
style = "fg:color_fg0 bg:color_bg1"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "
NixOS = " "

[env_var]
symbol = "╭╴"
variable = 'SHELL'
style = "fg:color_fg0"
format = "[$symbol]($style)"
disabled = false

[directory]
style = "fg:color_fg0 bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = ""

[git_branch]
symbol = " "
style = "bg:color_bg1"
format = '[[ $branch $symbol](fg:color_fg0 bg:color_bg1)]($style)'

[git_status]
style = "bg:color_bg1"
format = '[[($all_status$ahead_behind)](fg:color_red bg:color_bg1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_yellow"
format = '[[$time  ](fg:color_bg1 bg:color_yellow)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[[╰](fg:color_fg0)](bold fg:color_green)'
error_symbol = '[[╰](fg:color_fg0)](bold fg:color_red)'
vimcmd_symbol = '[[╰](fg:color_fg0)](bold fg:color_green)'
vimcmd_replace_one_symbol = '[[╰](fg:color_fg0)](bold fg:color_purple)'
vimcmd_replace_symbol = '[[╰](fg:color_fg0)](bold fg:color_purple)'
vimcmd_visual_symbol = '[[╰](fg:color_fg0)](bold fg:color_yellow)'
