"$schema" = 'https://starship.rs/config-schema.json'

format = """
$env_var\
[](5)\
${custom.start_symbol}\
$directory\
[](fg:5)\
$fill\
[](fg:5)\
$git_status\
$git_branch\
${custom.end_symbol}\
[ ](fg:5)\
$line_break$character"""

[fill]
symbol = '·'
style = 'fg:5'

[env_var]
symbol = "╭╴"
variable = 'SHELL'
style = "fg:7"
format = "[$symbol]($style)"
disabled = false

[directory]
style = "bold fg:0 bg:5"
format = "[$path ]($style)"
truncation_length = 0
truncation_symbol = ""

[git_branch]
style = "bg:5"
format = '[[ $branch](bold fg:0 bg:5)]($style)'

[git_status]
style = "bg:1"
format = '[[( $all_status$ahead_behind)](bold fg:1 bg:5)]($style)'

[custom.end_symbol]
command = "echo ''"
when = "true"
style = "bold fg:0 bg:5"
format = '[ $output ]($style)'

[custom.start_symbol]
command = "echo ' '"
when = "true"
style = "bold fg:0 bg:5"
format = '[$output ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[[╰](fg:7)](bold fg:2)'
error_symbol = '[[╰](fg:7)](bold fg:1)'
vimcmd_symbol = '[[╰](fg:7)](bold fg:2)'
vimcmd_replace_one_symbol = '[[╰](fg:7)](bold fg:5)'
vimcmd_replace_symbol = '[[╰](fg:7)](bold fg:5)'
vimcmd_visual_symbol = '[[╰](fg:7)](bold fg:3)'
